const TEAMS = [
  { id: "ARS", name: "Arsenal" },
  { id: "AVL", name: "Aston Villa" },
  { id: "BOU", name: "AFC Bournemouth" },
  { id: "BRE", name: "Brentford" },
  { id: "BHA", name: "Brighton & Hove Albion" },
  { id: "CHE", name: "Chelsea" },
  { id: "CRY", name: "Crystal Palace" },
  { id: "EVE", name: "Everton" },
  { id: "FUL", name: "Fulham" },
  { id: "LIV", name: "Liverpool FC" },
  { id: "MCI", name: "Manchester City" },
  { id: "MUN", name: "Manchester United" },
  { id: "NEW", name: "Newcastle United" },
  { id: "NFO", name: "Nottingham Forest" },
  { id: "TOT", name: "Tottenham Hotspur" },
  { id: "WHU", name: "West Ham United" },
  { id: "WOL", name: "Wolverhampton Wanderers" },
  { id: "BUR", name: "Burnley" },
  { id: "LEE", name: "Leeds" },
  { id: "SUN", name: "Sunderland" },
];

const CATEGORIES = [
  { id: "base", name: "Base Set", prefix: "" },
  { id: "pro-partnerships", name: "Pro Partnerships", prefix: "" },
  { id: "retro-threads", name: "Retro Threads", prefix: "" },
  { id: "pro-precision", name: "Pro Precision", prefix: "" },
  { id: "beast-mode", name: "Beast Mode", prefix: "" },
  { id: "headlines", name: "Headlines", prefix: "" },
  { id: "base-autographs", name: "Base Autographs", prefix: "BA" },
  { id: "beast-mode-autographs", name: "Beast Mode Autographs", prefix: "BMA" },
  { id: "chrome-kings-autographs", name: "Chrome Kings Autographs", prefix: "CKA" },
  { id: "black-edge-autographs", name: "Black Edge Edition Autographs", prefix: "BEA" },
  { id: "premier-relics", name: "Premier Relics", prefix: "PR" },
  { id: "chrome-kings", name: "Chrome Kings", prefix: "CK" },
  { id: "gold-lions", name: "Gold Lions", prefix: "GL" },
  { id: "classic-limited-editions", name: "Classic Limited Editions", prefix: "LE" },
  { id: "goal-machine", name: "Goal Machine", prefix: "GM" },
  { id: "globaller", name: "Globaller", prefix: "WC" },
  { id: "big-game-baller", name: "Big Game Baller", prefix: "BGB" },
  { id: "hall-of-fame", name: "Hall Of Fame", prefix: "HOF" },
  { id: "golden-boot", name: "Golden Boot", prefix: "GB" },
  { id: "festive-freeze", name: "Festive Freeze", prefix: "FF" },
  { id: "diamond-rookie-cards", name: "Diamond Rookie Cards", prefix: "DRC" },
  { id: "premier-pulls", name: "Premier Pulls", prefix: "PP" },
  { id: "black-edge-edition", name: "Black Edge Edition", prefix: "BE" },
  { id: "perfect-storm", name: "Perfect Storm", prefix: "PS" },
  { id: "heat-vision", name: "Heat Vision", prefix: "HV" },
  { id: "home-advantage", name: "Home Advantage", prefix: "HA" },
];

const CARDS = [
  { number: "1", name: "Team Badge", team: "ARS", category: "base" },
  { number: "2", name: "David Raya", team: "ARS", category: "base" },
  { number: "3", name: "William Saliba", team: "ARS", category: "base" },
  { number: "4", name: "Gabriel Magalhães", team: "ARS", category: "base" },
  { number: "5", name: "Jurriën Timber", team: "ARS", category: "base" },
  { number: "6", name: "Mikel Merino", team: "ARS", category: "base" },
  { number: "7", name: "Thomas Partey", team: "ARS", category: "base" },
  { number: "8", name: "Declan Rice", team: "ARS", category: "base" },
  { number: "9", name: "Myles Lewis-Skelly", team: "ARS", category: "base" },
  { number: "10", name: "Martin Ødegaard", team: "ARS", category: "base" },
  { number: "11", name: "Ethan Nwaneri", team: "ARS", category: "base" },
  { number: "12", name: "Bukayo Saka", team: "ARS", category: "base" },
  { number: "13", name: "Gabriel Martinelli", team: "ARS", category: "base" },
  { number: "14", name: "Leandro Trossard", team: "ARS", category: "base" },
  { number: "15", name: "Kai Havertz", team: "ARS", category: "base" },
  { number: "16", name: "Gabriel Martinelli", team: "ARS", category: "base", tag: "Generation Now" },
  { number: "17", name: "Jurriën Timber", team: "ARS", category: "base", tag: "Full Force" },
  { number: "18", name: "Myles Lewis-Skelly", team: "ARS", category: "base", tag: "Breakthrough Baller" },
  { number: "19", name: "Team Badge", team: "AVL", category: "base" },
  { number: "20", name: "Emiliano Martínez", team: "AVL", category: "base" },
  { number: "21", name: "Pau Torres", team: "AVL", category: "base" },
  { number: "22", name: "Ezri Konsa", team: "AVL", category: "base" },
  { number: "23", name: "Matty Cash", team: "AVL", category: "base" },
  { number: "24", name: "Lucas Digne", team: "AVL", category: "base" },
  { number: "25", name: "Boubacar Kamara", team: "AVL", category: "base" },
  { number: "26", name: "Amadou Onana", team: "AVL", category: "base" },
  { number: "27", name: "John McGinn", team: "AVL", category: "base" },
  { number: "28", name: "Youri Tielemans", team: "AVL", category: "base" },
  { number: "29", name: "Jacob Ramsey", team: "AVL", category: "base" },
  { number: "30", name: "Morgan Rogers", team: "AVL", category: "base" },
  { number: "31", name: "Louie Barry", team: "AVL", category: "base", tag: "RC" },
  { number: "32", name: "Donyell Malen", team: "AVL", category: "base" },
  { number: "33", name: "Ollie Watkins", team: "AVL", category: "base" },
  { number: "34", name: "Boubacar Kamara", team: "AVL", category: "base", tag: "Generation Now" },
  { number: "35", name: "John McGinn", team: "AVL", category: "base", tag: "Full Force" },
  { number: "36", name: "Donyell Malen", team: "AVL", category: "base", tag: "Tekkers" },
  { number: "37", name: "Team Badge", team: "BOU", category: "base" },
  { number: "38", name: "Kepa Arrizabalaga", team: "BOU", category: "base" },
  { number: "39", name: "Illia Zabarnyi", team: "BOU", category: "base" },
  { number: "40", name: "Dean Huijsen", team: "BOU", category: "base" },
  { number: "41", name: "Julio Soler", team: "BOU", category: "base", tag: "RC" },
  { number: "42", name: "Milos Kerkez", team: "BOU", category: "base" },
  { number: "43", name: "Tyler Adams", team: "BOU", category: "base" },
  { number: "44", name: "Lewis Cook", team: "BOU", category: "base" },
  { number: "45", name: "Ryan Christie", team: "BOU", category: "base" },
  { number: "46", name: "Luis Sinisterra", team: "BOU", category: "base" },
  { number: "47", name: "Antoine Semenyo", team: "BOU", category: "base" },
  { number: "48", name: "Justin Kluivert", team: "BOU", category: "base" },
  { number: "49", name: "Eli Junior Kroupi", team: "BOU", category: "base" },
  { number: "50", name: "Dango Ouattara", team: "BOU", category: "base" },
  { number: "51", name: "Evanilson", team: "BOU", category: "base" },
  { number: "52", name: "Milos Kerkez", team: "BOU", category: "base", tag: "Generation Now" },
  { number: "53", name: "Illia Zabarnyi", team: "BOU", category: "base", tag: "Full Force" },
  { number: "54", name: "Justin Kluivert", team: "BOU", category: "base", tag: "Tekkers" },
  { number: "55", name: "Team Badge", team: "BRE", category: "base" },
  { number: "56", name: "Mark Flekken", team: "BRE", category: "base" },
  { number: "57", name: "Nathan Collins", team: "BRE", category: "base" },
  { number: "58", name: "Sepp van den Berg", team: "BRE", category: "base" },
  { number: "59", name: "Michael Kayode", team: "BRE", category: "base" },
  { number: "60", name: "Christian Nørgaard", team: "BRE", category: "base" },
  { number: "61", name: "Mathias Jensen", team: "BRE", category: "base" },
  { number: "62", name: "Vitaly Janelt", team: "BRE", category: "base" },
  { number: "63", name: "Mikkel Damsgaard", team: "BRE", category: "base" },
  { number: "64", name: "Fábio Carvalho", team: "BRE", category: "base" },
  { number: "65", name: "Kevin Schade", team: "BRE", category: "base" },
  { number: "66", name: "Keane Lewis-Potter", team: "BRE", category: "base" },
  { number: "67", name: "Gustavo Nunes", team: "BRE", category: "base", tag: "RC" },
  { number: "68", name: "Bryan Mbeumo", team: "BRE", category: "base" },
  { number: "69", name: "Yoane Wissa", team: "BRE", category: "base" },
  { number: "70", name: "Fábio Carvalho", team: "BRE", category: "base", tag: "Generation Now" },
  { number: "71", name: "Gustavo Nunes", team: "BRE", category: "base", tag: "Full Force" },
  { number: "72", name: "Kevin Schade", team: "BRE", category: "base", tag: "Tekkers" },
  { number: "73", name: "Team Badge", team: "BHA", category: "base" },
  { number: "74", name: "Bart Verbruggen", team: "BHA", category: "base" },
  { number: "75", name: "Jan Paul van Hecke", team: "BHA", category: "base" },
  { number: "76", name: "Pervis Estupiñán", team: "BHA", category: "base" },
  { number: "77", name: "Lewis Dunk", team: "BHA", category: "base" },
  { number: "78", name: "Jack Hinshelwood", team: "BHA", category: "base" },
  { number: "79", name: "Yankuba Minteh", team: "BHA", category: "base" },
  { number: "80", name: "Carlos Baleba", team: "BHA", category: "base" },
  { number: "81", name: "Yoon Do-young", team: "BHA", category: "base", tag: "RC" },
  { number: "82", name: "Yasin Ayari", team: "BHA", category: "base", tag: "RC" },
  { number: "83", name: "Kaoru Mitoma", team: "BHA", category: "base" },
  { number: "84", name: "Stefanos Tzimas", team: "BHA", category: "base", tag: "RC" },
  { number: "85", name: "Danny Welbeck", team: "BHA", category: "base" },
  { number: "86", name: "Georginio Rutter", team: "BHA", category: "base" },
  { number: "87", name: "João Pedro", team: "BHA", category: "base" },
  { number: "88", name: "Matt O’Riley", team: "BHA", category: "base", tag: "Generation Now" },
  { number: "89", name: "Carlos Baleba", team: "BHA", category: "base", tag: "Full Force" },
  { number: "90", name: "Matt O’Riley", team: "BHA", category: "base", tag: "Tekkers" },
  { number: "91", name: "Team Badge", team: "CHE", category: "base" },
  { number: "92", name: "Robert Sánchez", team: "CHE", category: "base" },
  { number: "93", name: "Levi Colwill", team: "CHE", category: "base" },
  { number: "94", name: "Tosin Adarabioyo", team: "CHE", category: "base" },
  { number: "95", name: "Reece James", team: "CHE", category: "base" },
  { number: "96", name: "Marc Cucurella", team: "CHE", category: "base" },
  { number: "97", name: "Harrison Murray-Campbell", team: "CHE", category: "base", tag: "RC" },
  { number: "98", name: "Moisés Caicedo", team: "CHE", category: "base" },
  { number: "99", name: "Enzo Fernández", team: "CHE", category: "base" },
  { number: "100", name: "Cole Palmer", team: "CHE", category: "base" },
  { number: "101", name: "Kendry Páez", team: "CHE", category: "base", tag: "RC" },
  { number: "102", name: "Pedro Neto", team: "CHE", category: "base" },
  { number: "103", name: "Noni Madueke", team: "CHE", category: "base" },
  { number: "104", name: "Nicolas Jackson", team: "CHE", category: "base" },
  { number: "105", name: "Estêvão", team: "CHE", category: "base", tag: "RC" },
  { number: "106", name: "Levi Colwill", team: "CHE", category: "base", tag: "Generation Now" },
  { number: "107", name: "Marc Cucurella", team: "CHE", category: "base", tag: "Full Force" },
  { number: "108", name: "Noni Madueke", team: "CHE", category: "base", tag: "Tekkers" },
  { number: "109", name: "Team Badge", team: "CRY", category: "base" },
  { number: "110", name: "Dean Henderson", team: "CRY", category: "base" },
  { number: "111", name: "Tyrick Mitchell", team: "CRY", category: "base" },
  { number: "112", name: "Chadi Riad", team: "CRY", category: "base" },
  { number: "113", name: "Maxence Lacroix", team: "CRY", category: "base" },
  { number: "114", name: "Marc Guéhi", team: "CRY", category: "base" },
  { number: "115", name: "Chris Richards", team: "CRY", category: "base" },
  { number: "116", name: "Daniel Muñoz", team: "CRY", category: "base" },
  { number: "117", name: "Adam Wharton", team: "CRY", category: "base" },
  { number: "118", name: "Romain Esse", team: "CRY", category: "base", tag: "RC" },
  { number: "119", name: "Daichi Kamada", team: "CRY", category: "base" },
  { number: "120", name: "Eberechi Eze", team: "CRY", category: "base" },
  { number: "121", name: "Ismaïla Sarr", team: "CRY", category: "base" },
  { number: "122", name: "Eddie Nketiah", team: "CRY", category: "base" },
  { number: "123", name: "Jean-Philippe Mateta", team: "CRY", category: "base" },
  { number: "124", name: "Marc Guéhi", team: "CRY", category: "base", tag: "Generation Now" },
  { number: "125", name: "Tyrick Mitchell", team: "CRY", category: "base", tag: "Full Force" },
  { number: "126", name: "Ismaïla Sarr", team: "CRY", category: "base", tag: "Tekkers" },
  { number: "127", name: "Team Badge", team: "EVE", category: "base" },
  { number: "128", name: "Jordan Pickford", team: "EVE", category: "base" },
  { number: "129", name: "James Tarkowski", team: "EVE", category: "base" },
  { number: "130", name: "Jarrad Branthwaite", team: "EVE", category: "base" },
  { number: "131", name: "Vitalii Mykolenko", team: "EVE", category: "base" },
  { number: "132", name: "Jake O’Brien", team: "EVE", category: "base" },
  { number: "133", name: "Nathan Patterson", team: "EVE", category: "base" },
  { number: "134", name: "Roman Dixon", team: "EVE", category: "base", tag: "RC" },
  { number: "135", name: "Tim Iroegbunam", team: "EVE", category: "base" },
  { number: "136", name: "Harrison Armstrong", team: "EVE", category: "base", tag: "RC" },
  { number: "137", name: "James Garner", team: "EVE", category: "base" },
  { number: "138", name: "Dwight McNeil", team: "EVE", category: "base" },
  { number: "139", name: "Iliman Ndiaye", team: "EVE", category: "base" },
  { number: "140", name: "Beto", team: "EVE", category: "base" },
  { number: "141", name: "Youssef Chermiti", team: "EVE", category: "base" },
  { number: "142", name: "Iliman Ndiaye", team: "EVE", category: "base", tag: "Generation Now" },
  { number: "143", name: "Vitalii Mykolenko", team: "EVE", category: "base", tag: "Full Force" },
  { number: "144", name: "Iliman Ndiaye", team: "EVE", category: "base", tag: "Tekkers" },
  { number: "145", name: "Team Badge", team: "FUL", category: "base" },
  { number: "146", name: "Bernd Leno", team: "FUL", category: "base" },
  { number: "147", name: "Calvin Bassey", team: "FUL", category: "base" },
  { number: "148", name: "Joachim Andersen", team: "FUL", category: "base" },
  { number: "149", name: "Sander Berge", team: "FUL", category: "base" },
  { number: "150", name: "Antonee Robinson", team: "FUL", category: "base" },
  { number: "151", name: "Saša Lukić", team: "FUL", category: "base" },
  { number: "152", name: "Josh King", team: "FUL", category: "base", tag: "RC" },
  { number: "153", name: "Andreas Pereira", team: "FUL", category: "base" },
  { number: "154", name: "Alex Iwobi", team: "FUL", category: "base" },
  { number: "155", name: "Emile Smith Rowe", team: "FUL", category: "base" },
  { number: "156", name: "Harry Wilson", team: "FUL", category: "base" },
  { number: "157", name: "Adama Traoré", team: "FUL", category: "base" },
  { number: "158", name: "Rodrigo Muniz", team: "FUL", category: "base" },
  { number: "159", name: "Raúl Jiménez", team: "FUL", category: "base" },
  { number: "160", name: "Rodrigo Muniz", team: "FUL", category: "base", tag: "Generation Now" },
  { number: "161", name: "Calvin Bassey", team: "FUL", category: "base", tag: "Full Force" },
  { number: "162", name: "Josh King", team: "FUL", category: "base", tag: "Breakthrough Baller" },
  { number: "163", name: "Team Badge", team: "LIV", category: "base" },
  { number: "164", name: "Alisson Becker", team: "LIV", category: "base" },
  { number: "165", name: "Virgil van Dijk", team: "LIV", category: "base" },
  { number: "166", name: "Ibrahima Konaté", team: "LIV", category: "base" },
  { number: "167", name: "Andy Robertson", team: "LIV", category: "base" },
  { number: "168", name: "Conor Bradley", team: "LIV", category: "base" },
  { number: "169", name: "Ryan Gravenberch", team: "LIV", category: "base" },
  { number: "170", name: "Alexis Mac Allister", team: "LIV", category: "base" },
  { number: "171", name: "Dominik Szoboszlai", team: "LIV", category: "base" },
  { number: "172", name: "Rio Ngumoha", team: "LIV", category: "base", tag: "RC" },
  { number: "173", name: "Luis Díaz", team: "LIV", category: "base" },
  { number: "174", name: "Mohamed Salah", team: "LIV", category: "base" },
  { number: "175", name: "Cody Gakpo", team: "LIV", category: "base" },
  { number: "176", name: "Diogo Jota", team: "LIV", category: "base" },
  { number: "177", name: "Darwin Núñez", team: "LIV", category: "base" },
  { number: "178", name: "Dominik Szoboszlai", team: "LIV", category: "base", tag: "Generation Now" },
  { number: "179", name: "Darwin Núñez", team: "LIV", category: "base", tag: "Full Force" },
  { number: "180", name: "Luis Díaz", team: "LIV", category: "base", tag: "Tekkers" },
  { number: "181", name: "Team Badge", team: "MCI", category: "base" },
  { number: "182", name: "Ederson", team: "MCI", category: "base" },
  { number: "183", name: "Rúben Dias", team: "MCI", category: "base" },
  { number: "184", name: "Joško Gvardiol", team: "MCI", category: "base" },
  { number: "185", name: "Vitor Reis", team: "MCI", category: "base", tag: "RC" },
  { number: "186", name: "Divine Mukasa", team: "MCI", category: "base", tag: "RC" },
  { number: "187", name: "Nico González", team: "MCI", category: "base" },
  { number: "188", name: "Rodri", team: "MCI", category: "base" },
  { number: "189", name: "Jérémy Doku", team: "MCI", category: "base" },
  { number: "190", name: "Phil Foden", team: "MCI", category: "base" },
  { number: "191", name: "Bernardo Silva", team: "MCI", category: "base" },
  { number: "192", name: "Sávio", team: "MCI", category: "base" },
  { number: "193", name: "Reigan Heskey", team: "MCI", category: "base", tag: "RC" },
  { number: "194", name: "Omar Marmoush", team: "MCI", category: "base" },
  { number: "195", name: "Erling Haaland", team: "MCI", category: "base" },
  { number: "196", name: "Jérémy Doku", team: "MCI", category: "base", tag: "Generation Now" },
  { number: "197", name: "Joško Gvardiol", team: "MCI", category: "base", tag: "Full Force" },
  { number: "198", name: "Sávio", team: "MCI", category: "base", tag: "Tekkers" },
  { number: "199", name: "Team Badge", team: "MUN", category: "base" },
  { number: "200", name: "André Onana", team: "MUN", category: "base" },
  { number: "201", name: "Matthijs de Ligt", team: "MUN", category: "base" },
  { number: "202", name: "Leny Yoro", team: "MUN", category: "base" },
  { number: "203", name: "Lisandro Martínez", team: "MUN", category: "base" },
  { number: "204", name: "Diogo Dalot", team: "MUN", category: "base" },
  { number: "205", name: "Sékou Koné", team: "MUN", category: "base", tag: "RC" },
  { number: "206", name: "Kobbie Mainoo", team: "MUN", category: "base" },
  { number: "207", name: "Manuel Ugarte", team: "MUN", category: "base" },
  { number: "208", name: "Bruno Fernandes", team: "MUN", category: "base" },
  { number: "209", name: "Shea Lacey", team: "MUN", category: "base", tag: "RC" },
  { number: "210", name: "Alejandro Garnacho", team: "MUN", category: "base" },
  { number: "211", name: "Amad", team: "MUN", category: "base" },
  { number: "212", name: "Joshua Zirkzee", team: "MUN", category: "base" },
  { number: "213", name: "Rasmus Højlund", team: "MUN", category: "base" },
  { number: "214", name: "Kobbie Mainoo", team: "MUN", category: "base", tag: "Generation Now" },
  { number: "215", name: "Manuel Ugarte", team: "MUN", category: "base", tag: "Full Force" },
  { number: "216", name: "Patrick Dorgu", team: "MUN", category: "base", tag: "Breakthrough Baller" },
  { number: "217", name: "Team Badge", team: "NEW", category: "base" },
  { number: "218", name: "Nick Pope", team: "NEW", category: "base" },
  { number: "219", name: "Dan Burn", team: "NEW", category: "base" },
  { number: "220", name: "Sven Botman", team: "NEW", category: "base" },
  { number: "221", name: "Fabian Schär", team: "NEW", category: "base" },
  { number: "222", name: "Tino Livramento", team: "NEW", category: "base" },
  { number: "223", name: "Lewis Hall", team: "NEW", category: "base" },
  { number: "224", name: "Lewis Miley", team: "NEW", category: "base" },
  { number: "225", name: "Sandro Tonali", team: "NEW", category: "base" },
  { number: "226", name: "Joelinton", team: "NEW", category: "base" },
  { number: "227", name: "Bruno Guimarães", team: "NEW", category: "base" },
  { number: "228", name: "Jacob Murphy", team: "NEW", category: "base" },
  { number: "229", name: "Harvey Barnes", team: "NEW", category: "base" },
  { number: "230", name: "Anthony Gordon", team: "NEW", category: "base" },
  { number: "231", name: "Alexander Isak", team: "NEW", category: "base" },
  { number: "232", name: "Tino Livramento", team: "NEW", category: "base", tag: "Generation Now" },
  { number: "233", name: "Joelinton", team: "NEW", category: "base", tag: "Full Force" },
  { number: "234", name: "Lewis Miley", team: "NEW", category: "base", tag: "Breakthrough Baller" },
  { number: "235", name: "Team Badge", team: "NFO", category: "base" },
  { number: "236", name: "Matz Sels", team: "NFO", category: "base" },
  { number: "237", name: "Nikola Milenković", team: "NFO", category: "base" },
  { number: "238", name: "Ola Aina", team: "NFO", category: "base" },
  { number: "239", name: "Murillo", team: "NFO", category: "base" },
  { number: "240", name: "Neco Williams", team: "NFO", category: "base" },
  { number: "241", name: "Zach Abbott", team: "NFO", category: "base", tag: "RC" },
  { number: "242", name: "Ryan Yates", team: "NFO", category: "base" },
  { number: "243", name: "Ibrahim Sangaré", team: "NFO", category: "base" },
  { number: "244", name: "Elliot Anderson", team: "NFO", category: "base" },
  { number: "245", name: "Morgan Gibbs-White", team: "NFO", category: "base" },
  { number: "246", name: "Callum Hudson-Odoi", team: "NFO", category: "base" },
  { number: "247", name: "Anthony Elanga", team: "NFO", category: "base" },
  { number: "248", name: "Taiwo Awoniyi", team: "NFO", category: "base" },
  { number: "249", name: "Chris Wood", team: "NFO", category: "base" },
  { number: "250", name: "Murillo", team: "NFO", category: "base", tag: "Generation Now" },
  { number: "251", name: "Ola Aina", team: "NFO", category: "base", tag: "Full Force" },
  { number: "252", name: "Anthony Elanga", team: "NFO", category: "base", tag: "Tekkers" },
  { number: "253", name: "Team Badge", team: "TOT", category: "base" },
  { number: "254", name: "Antonín Kinský", team: "TOT", category: "base", tag: "RC" },
  { number: "255", name: "Pedro Porro", team: "TOT", category: "base" },
  { number: "256", name: "Micky van de Ven", team: "TOT", category: "base" },
  { number: "257", name: "Cristian Romero", team: "TOT", category: "base" },
  { number: "258", name: "Destiny Udogie", team: "TOT", category: "base" },
  { number: "259", name: "Archie Gray", team: "TOT", category: "base" },
  { number: "260", name: "Dejan Kulusevski", team: "TOT", category: "base" },
  { number: "261", name: "Lucas Bergvall", team: "TOT", category: "base" },
  { number: "262", name: "James Maddison", team: "TOT", category: "base" },
  { number: "263", name: "Will Lankshear", team: "TOT", category: "base", tag: "RC" },
  { number: "264", name: "Son Heung-Min", team: "TOT", category: "base" },
  { number: "265", name: "Brennan Johnson", team: "TOT", category: "base" },
  { number: "266", name: "Mikey Moore", team: "TOT", category: "base" },
  { number: "267", name: "Dominic Solanke", team: "TOT", category: "base" },
  { number: "268", name: "Lucas Bergvall", team: "TOT", category: "base", tag: "Generation Now" },
  { number: "269", name: "Mikey Moore", team: "TOT", category: "base", tag: "Full Force" },
  { number: "270", name: "Archie Gray", team: "TOT", category: "base", tag: "Breakthrough Baller" },
  { number: "271", name: "Team Badge", team: "WHU", category: "base" },
  { number: "272", name: "Alphonse Areola", team: "WHU", category: "base" },
  { number: "273", name: "Jean-Clair Todibo", team: "WHU", category: "base" },
  { number: "274", name: "Maximilian Kilman", team: "WHU", category: "base" },
  { number: "275", name: "Aaron Wan-Bissaka", team: "WHU", category: "base" },
  { number: "276", name: "Emerson Palmieri", team: "WHU", category: "base" },
  { number: "277", name: "Oliver Scarles", team: "WHU", category: "base" },
  { number: "278", name: "Tomáš Souček", team: "WHU", category: "base" },
  { number: "279", name: "Edson Álvarez", team: "WHU", category: "base" },
  { number: "280", name: "Guido Rodríguez", team: "WHU", category: "base" },
  { number: "281", name: "Mohammed Kudus", team: "WHU", category: "base" },
  { number: "282", name: "Niclas Füllkrug", team: "WHU", category: "base" },
  { number: "283", name: "Crysencio Summerville", team: "WHU", category: "base" },
  { number: "284", name: "Jarrod Bowen", team: "WHU", category: "base" },
  { number: "285", name: "Luis Guilherme", team: "WHU", category: "base", tag: "RC" },
  { number: "286", name: "Crysencio Summerville", team: "WHU", category: "base", tag: "Generation Now" },
  { number: "287", name: "Aaron Wan-Bissaka", team: "WHU", category: "base", tag: "Full Force" },
  { number: "288", name: "Luis Guilherme", team: "WHU", category: "base", tag: "Breakthrough Baller" },
  { number: "289", name: "Team Badge", team: "WOL", category: "base" },
  { number: "290", name: "José Sá", team: "WOL", category: "base" },
  { number: "291", name: "Nélson Semedo", team: "WOL", category: "base" },
  { number: "292", name: "Nasser Djiga", team: "WOL", category: "base", tag: "RC" },
  { number: "293", name: "Emmanuel Agbadou", team: "WOL", category: "base" },
  { number: "294", name: "Toti Gomes", team: "WOL", category: "base" },
  { number: "295", name: "Rayan Aït-Nouri", team: "WOL", category: "base" },
  { number: "296", name: "Marshall Munetsi", team: "WOL", category: "base" },
  { number: "297", name: "André", team: "WOL", category: "base" },
  { number: "298", name: "João Gomes", team: "WOL", category: "base" },
  { number: "299", name: "Rodrigo Gomes", team: "WOL", category: "base" },
  { number: "300", name: "Gonçalo Guedes", team: "WOL", category: "base" },
  { number: "301", name: "Hwang Hee-Chan", team: "WOL", category: "base" },
  { number: "302", name: "Jørgen Strand Larsen", team: "WOL", category: "base" },
  { number: "303", name: "Matheus Cunha", team: "WOL", category: "base" },
  { number: "304", name: "João Gomes", team: "WOL", category: "base", tag: "Generation Now" },
  { number: "305", name: "Nasser Djiga", team: "WOL", category: "base", tag: "Full Force" },
  { number: "306", name: "André", team: "WOL", category: "base", tag: "Breakthrough Baller" },
  { number: "307", name: "Team Badge", team: "BUR", category: "base" },
  { number: "308", name: "James Trafford", team: "BUR", category: "base" },
  { number: "309", name: "Maxime Estève", team: "BUR", category: "base" },
  { number: "310", name: "Bashir Humphreys", team: "BUR", category: "base", tag: "RC" },
  { number: "311", name: "Connor Roberts", team: "BUR", category: "base" },
  { number: "312", name: "Lucas Pires", team: "BUR", category: "base" },
  { number: "313", name: "Josh Laurent", team: "BUR", category: "base", tag: "RC" },
  { number: "314", name: "Josh Cullen", team: "BUR", category: "base" },
  { number: "315", name: "Josh Brownhill", team: "BUR", category: "base" },
  { number: "316", name: "Hannibal", team: "BUR", category: "base" },
  { number: "317", name: "Marcus Edwards", team: "BUR", category: "base" },
  { number: "318", name: "Lyle Foster", team: "BUR", category: "base" },
  { number: "319", name: "Luca Koleosho", team: "BUR", category: "base" },
  { number: "320", name: "Jaidon Anthony", team: "BUR", category: "base" },
  { number: "321", name: "Jaydon Banel", team: "BUR", category: "base", tag: "RC" },
  { number: "322", name: "Lucas Pires", team: "BUR", category: "base", tag: "Generation Now" },
  { number: "323", name: "Josh Cullen", team: "BUR", category: "base", tag: "Full Force" },
  { number: "324", name: "Luca Koleosho", team: "BUR", category: "base", tag: "Breakthrough Baller" },
  { number: "325", name: "Team Badge", team: "LEE", category: "base" },
  { number: "326", name: "Illan Meslier", team: "LEE", category: "base" },
  { number: "327", name: "Joe Rodon", team: "LEE", category: "base" },
  { number: "328", name: "Pascal Struijk", team: "LEE", category: "base" },
  { number: "329", name: "Jayden Bogle", team: "LEE", category: "base" },
  { number: "330", name: "Ethan Ampadu", team: "LEE", category: "base" },
  { number: "331", name: "Ao Tanaka", team: "LEE", category: "base" },
  { number: "332", name: "Brenden Aaronson", team: "LEE", category: "base" },
  { number: "333", name: "Ilia Gruev", team: "LEE", category: "base" },
  { number: "334", name: "Harry Gray", team: "LEE", category: "base", tag: "RC" },
  { number: "335", name: "Mateo Joseph", team: "LEE", category: "base", tag: "RC" },
  { number: "336", name: "Wilfried Gnonto", team: "LEE", category: "base" },
  { number: "337", name: "Daniel James", team: "LEE", category: "base" },
  { number: "338", name: "Patrick Bamford", team: "LEE", category: "base" },
  { number: "339", name: "Joël Piroe", team: "LEE", category: "base", tag: "RC" },
  { number: "340", name: "Mateo Joseph", team: "LEE", category: "base", tag: "Generation Now" },
  { number: "341", name: "Pascal Struijk", team: "LEE", category: "base", tag: "Full Force" },
  { number: "342", name: "Harry Gray", team: "LEE", category: "base", tag: "Breakthrough Baller" },
  { number: "343", name: "Team Badge", team: "SUN", category: "base" },
  { number: "344", name: "Anthony Patterson", team: "SUN", category: "base", tag: "RC" },
  { number: "345", name: "Trai Hume", team: "SUN", category: "base", tag: "RC" },
  { number: "346", name: "Dennis Cirkin", team: "SUN", category: "base", tag: "RC" },
  { number: "347", name: "Luke O’Nien", team: "SUN", category: "base", tag: "RC" },
  { number: "348", name: "Daniel Ballard", team: "SUN", category: "base", tag: "RC" },
  { number: "349", name: "Chris Rigg", team: "SUN", category: "base", tag: "RC" },
  { number: "350", name: "Dan Neil", team: "SUN", category: "base", tag: "RC" },
  { number: "351", name: "Alan Browne", team: "SUN", category: "base", tag: "RC" },
  { number: "352", name: "Jobe Bellingham", team: "SUN", category: "base", tag: "RC" },
  { number: "353", name: "Enzo Le Fée", team: "SUN", category: "base" },
  { number: "354", name: "Romaine Mundle", team: "SUN", category: "base", tag: "RC" },
  { number: "355", name: "Patrick Roberts", team: "SUN", category: "base" },
  { number: "356", name: "Eliezer Mayenda", team: "SUN", category: "base", tag: "RC" },
  { number: "357", name: "Wilson Isidor", team: "SUN", category: "base", tag: "RC" },
  { number: "358", name: "Jobe Bellingham", team: "SUN", category: "base", tag: "Generation Now" },
  { number: "359", name: "Wilson Isidor", team: "SUN", category: "base", tag: "Full Force" },
  { number: "360", name: "Chris Rigg", team: "SUN", category: "base", tag: "Breakthrough Baller" },
  { number: "361", name: "William Saliba/Gabriel Magalhães", team: "ARS", category: "pro-partnerships" },
  { number: "362", name: "Amadou Onana/Youri Tielemans", team: "AVL", category: "pro-partnerships" },
  { number: "363", name: "Antoine Semenyo/Dango Ouattara", team: "BOU", category: "pro-partnerships" },
  { number: "364", name: "Nathan Collins/Sepp van den Berg", team: "BRE", category: "pro-partnerships" },
  { number: "365", name: "Kaoru Mitoma/Simon Adingra", team: "BHA", category: "pro-partnerships" },
  { number: "366", name: "Ricardo Carvalho/John Terry", team: "CHE", category: "pro-partnerships" },
  { number: "367", name: "Moisés Caicedo/Enzo Fernández", team: "CHE", category: "pro-partnerships" },
  { number: "368", name: "Daichi Kamada/Adam Wharton", team: "CRY", category: "pro-partnerships" },
  { number: "369", name: "James Tarkowski/Jarrad Branthwaite", team: "EVE", category: "pro-partnerships" },
  { number: "370", name: "Enzo Le Fée/Patrick Roberts", team: "SUN", category: "pro-partnerships" },
  { number: "371", name: "Ryan Gravenberch/Alexis Mac Allister", team: "LIV", category: "pro-partnerships" },
  { number: "372", name: "Phil Foden/Bernardo Silva", team: "MCI", category: "pro-partnerships" },
  { number: "373", name: "Bruno Fernandes/Rasmus Højlund", team: "MUN", category: "pro-partnerships" },
  { number: "374", name: "Bruno Guimarães/Joelinton", team: "NEW", category: "pro-partnerships" },
  { number: "375", name: "Ola Aina/Callum Hudson-Odoi", team: "NFO", category: "pro-partnerships" },
  { number: "376", name: "Brennan Johnson/Dejan Kulusevski", team: "TOT", category: "pro-partnerships" },
  { number: "377", name: "Darren Anderton/Teddy Sheringham", team: "TOT", category: "pro-partnerships" },
  { number: "378", name: "Gonçalo Guedes/Jørgen Strand Larsen", team: "WOL", category: "pro-partnerships" },
  { number: "379", name: "Maxime Estève/Lucas Pires", team: "BUR", category: "pro-partnerships" },
  { number: "380", name: "Joe Rodon/Ethan Ampadu", team: "LEE", category: "pro-partnerships" },
  { number: "381", name: "Ian Wright", team: "ARS", category: "retro-threads" },
  { number: "382", name: "Stiliyan Petrov", team: "AVL", category: "retro-threads" },
  { number: "383", name: "Simon Francis", team: "BOU", category: "retro-threads" },
  { number: "384", name: "Eric Cantona", team: "MUN", category: "retro-threads" },
  { number: "385", name: "Christian Nørgaard", team: "BRE", category: "retro-threads" },
  { number: "386", name: "Glenn Murray", team: "BHA", category: "retro-threads" },
  { number: "387", name: "Frank Lampard", team: "CHE", category: "retro-threads" },
  { number: "388", name: "Andrew Johnson", team: "CRY", category: "retro-threads" },
  { number: "389", name: "Joleon Lescott", team: "EVE", category: "retro-threads" },
  { number: "390", name: "Louis Saha", team: "FUL", category: "retro-threads" },
  { number: "391", name: "Jamie Carragher", team: "LIV", category: "retro-threads" },
  { number: "392", name: "Micah Richards", team: "MCI", category: "retro-threads" },
  { number: "393", name: "Gary Neville", team: "MUN", category: "retro-threads" },
  { number: "394", name: "Faustino Asprilla", team: "NEW", category: "retro-threads" },
  { number: "395", name: "Stan Collymore", team: "NFO", category: "retro-threads" },
  { number: "396", name: "Robbie Keane", team: "TOT", category: "retro-threads" },
  { number: "397", name: "Mark Noble", team: "WHU", category: "retro-threads" },
  { number: "398", name: "Kevin Doyle", team: "WOL", category: "retro-threads" },
  { number: "399", name: "Aaron Lennon", team: "BUR", category: "retro-threads" },
  { number: "400", name: "Jimmy Floyd Hasselbaink", team: "LEE", category: "retro-threads" },
  { number: "401", name: "Kai Havertz", team: "ARS", category: "pro-precision" },
  { number: "402", name: "Ollie Watkins", team: "AVL", category: "pro-precision" },
  { number: "403", name: "Dango Ouattara", team: "BOU", category: "pro-precision" },
  { number: "404", name: "Mikkel Damsgaard", team: "BRE", category: "pro-precision" },
  { number: "405", name: "Danny Welbeck", team: "BHA", category: "pro-precision" },
  { number: "406", name: "Nicolas Jackson", team: "CHE", category: "pro-precision" },
  { number: "407", name: "Eddie Nketiah", team: "CRY", category: "pro-precision" },
  { number: "408", name: "Beto", team: "EVE", category: "pro-precision" },
  { number: "409", name: "Robbie Fowler", team: "FUL", category: "pro-precision" },
  { number: "410", name: "Diogo Jota", team: "LIV", category: "pro-precision" },
  { number: "411", name: "Phil Foden", team: "MCI", category: "pro-precision" },
  { number: "412", name: "Bruno Fernandes", team: "MUN", category: "pro-precision" },
  { number: "413", name: "Wayne Rooney", team: "MUN", category: "pro-precision" },
  { number: "414", name: "Anthony Gordon", team: "NEW", category: "pro-precision" },
  { number: "415", name: "Taiwo Awoniyi", team: "NFO", category: "pro-precision" },
  { number: "416", name: "Brennan Johnson", team: "TOT", category: "pro-precision" },
  { number: "417", name: "Mohammed Kudus", team: "WHU", category: "pro-precision" },
  { number: "418", name: "Jørgen Strand Larsen", team: "WOL", category: "pro-precision" },
  { number: "419", name: "Josh Brownhill", team: "BUR", category: "pro-precision" },
  { number: "420", name: "Patrick Bamford", team: "LEE", category: "pro-precision" },
  { number: "421", name: "Declan Rice", team: "ARS", category: "beast-mode" },
  { number: "422", name: "Morgan Rogers", team: "AVL", category: "beast-mode" },
  { number: "423", name: "Evanilson", team: "BOU", category: "beast-mode" },
  { number: "424", name: "Yoane Wissa", team: "BRE", category: "beast-mode" },
  { number: "425", name: "Georginio Rutter", team: "BHA", category: "beast-mode" },
  { number: "426", name: "Enzo Fernández", team: "CHE", category: "beast-mode" },
  { number: "427", name: "Jean-Philippe Mateta", team: "CRY", category: "beast-mode" },
  { number: "428", name: "Beto", team: "EVE", category: "beast-mode" },
  { number: "429", name: "Ibrahima Konaté", team: "LIV", category: "beast-mode" },
  { number: "430", name: "Virgil van Dijk", team: "LIV", category: "beast-mode" },
  { number: "431", name: "Rodri", team: "MCI", category: "beast-mode" },
  { number: "432", name: "Alejandro Garnacho", team: "MUN", category: "beast-mode" },
  { number: "433", name: "Sandro Tonali", team: "NEW", category: "beast-mode" },
  { number: "434", name: "Chris Wood", team: "NFO", category: "beast-mode" },
  { number: "435", name: "Ledley King", team: "TOT", category: "beast-mode" },
  { number: "436", name: "Dominic Solanke", team: "TOT", category: "beast-mode" },
  { number: "437", name: "Emerson Palmieri", team: "WHU", category: "beast-mode" },
  { number: "438", name: "Hwang Hee-chan", team: "WOL", category: "beast-mode" },
  { number: "439", name: "Hannibal", team: "BUR", category: "beast-mode" },
  { number: "440", name: "Daniel James", team: "LEE", category: "beast-mode" },
  { number: "441", name: "Martin Ødegaard", team: "ARS", category: "headlines" },
  { number: "442", name: "Emiliano Martínez", team: "AVL", category: "headlines" },
  { number: "443", name: "Kevin Schade", team: "BRE", category: "headlines" },
  { number: "444", name: "Pedro Neto", team: "CHE", category: "headlines" },
  { number: "445", name: "Jordan Pickford", team: "EVE", category: "headlines" },
  { number: "446", name: "Cody Gakpo", team: "LIV", category: "headlines" },
  { number: "447", name: "Jérémy Doku", team: "MCI", category: "headlines" },
  { number: "448", name: "Amad", team: "MUN", category: "headlines" },
  { number: "449", name: "Jacob Murphy", team: "NEW", category: "headlines" },
  { number: "450", name: "James Maddison", team: "TOT", category: "headlines" },
  { number: "BA-1", name: "Dango Ouattara", team: "BOU", category: "base-autographs" },
  { number: "BA-2", name: "Evanilson", team: "BOU", category: "base-autographs" },
  { number: "BA-3", name: "Tyler Adams", team: "BOU", category: "base-autographs" },
  { number: "BA-4", name: "David Raya", team: "ARS", category: "base-autographs" },
  { number: "BA-5", name: "William Saliba", team: "ARS", category: "base-autographs" },
  { number: "BA-6", name: "Mikel Merino", team: "ARS", category: "base-autographs" },
  { number: "BA-7", name: "Declan Rice", team: "ARS", category: "base-autographs" },
  { number: "BA-8", name: "Myles Lewis-Skelly", team: "ARS", category: "base-autographs" },
  { number: "BA-9", name: "Martin Ødegaard", team: "ARS", category: "base-autographs" },
  { number: "BA-10", name: "Ethan Nwaneri", team: "ARS", category: "base-autographs" },
  { number: "BA-11", name: "Bukayo Saka", team: "ARS", category: "base-autographs" },
  { number: "BA-12", name: "Gabriel Martinelli", team: "ARS", category: "base-autographs" },
  { number: "BA-13", name: "Leandro Trossard", team: "ARS", category: "base-autographs" },
  { number: "BA-14", name: "Kai Havertz", team: "ARS", category: "base-autographs" },
  { number: "BA-15", name: "Donyell Malen", team: "AVL", category: "base-autographs" },
  { number: "BA-16", name: "Emiliano Martínez", team: "AVL", category: "base-autographs" },
  { number: "BA-17", name: "Jacob Ramsey", team: "AVL", category: "base-autographs" },
  { number: "BA-18", name: "Matty Cash", team: "AVL", category: "base-autographs" },
  { number: "BA-19", name: "Ollie Watkins", team: "AVL", category: "base-autographs" },
  { number: "BA-20", name: "Stiliyan Petrov", team: "AVL", category: "base-autographs" },
  { number: "BA-21", name: "Fábio Carvalho", team: "BRE", category: "base-autographs" },
  { number: "BA-22", name: "Kristoffer Ajer", team: "BRE", category: "base-autographs" },
  { number: "BA-23", name: "Kevin Schade", team: "BRE", category: "base-autographs" },
  { number: "BA-24", name: "Nathan Collins", team: "BRE", category: "base-autographs" },
  { number: "BA-25", name: "Yehor Yarmoliuk", team: "BRE", category: "base-autographs" },
  { number: "BA-26", name: "Evan Ferguson", team: "BHA", category: "base-autographs" },
  { number: "BA-27", name: "Georginio Rutter", team: "BHA", category: "base-autographs" },
  { number: "BA-28", name: "João Pedro", team: "BHA", category: "base-autographs" },
  { number: "BA-29", name: "Lewis Dunk", team: "BHA", category: "base-autographs" },
  { number: "BA-30", name: "Matt O’Riley", team: "BHA", category: "base-autographs" },
  { number: "BA-31", name: "Simon Adingra", team: "BHA", category: "base-autographs" },
  { number: "BA-32", name: "Yasin Ayari", team: "BHA", category: "base-autographs" },
  { number: "BA-33", name: "Yankuba Minteh", team: "BHA", category: "base-autographs" },
  { number: "BA-34", name: "Ashley Cole", team: "CHE", category: "base-autographs" },
  { number: "BA-35", name: "César Azpilicueta", team: "CHE", category: "base-autographs" },
  { number: "BA-36", name: "Cole Palmer", team: "CHE", category: "base-autographs" },
  { number: "BA-37", name: "Diego Costa", team: "CHE", category: "base-autographs" },
  { number: "BA-38", name: "Enzo Fernández", team: "CHE", category: "base-autographs" },
  { number: "BA-39", name: "Estêvão", team: "CHE", category: "base-autographs" },
  { number: "BA-40", name: "Juan Mata", team: "CHE", category: "base-autographs" },
  { number: "BA-41", name: "John Terry", team: "CHE", category: "base-autographs" },
  { number: "BA-42", name: "Levi Colwill", team: "CHE", category: "base-autographs" },
  { number: "BA-43", name: "Michael Ballack", team: "CHE", category: "base-autographs" },
  { number: "BA-44", name: "Nicolas Anelka", team: "CHE", category: "base-autographs" },
  { number: "BA-45", name: "Nicolas Jackson", team: "CHE", category: "base-autographs" },
  { number: "BA-46", name: "Noni Madueke", team: "CHE", category: "base-autographs" },
  { number: "BA-47", name: "Reece James", team: "CHE", category: "base-autographs" },
  { number: "BA-48", name: "Tosin Adarabioyo", team: "CHE", category: "base-autographs" },
  { number: "BA-49", name: "Tore André Flo", team: "CHE", category: "base-autographs" },
  { number: "BA-50", name: "Trevoh Chalobah", team: "CHE", category: "base-autographs" },
  { number: "BA-51", name: "Adam Wharton", team: "CRY", category: "base-autographs" },
  { number: "BA-52", name: "Chris Richards", team: "CRY", category: "base-autographs" },
  { number: "BA-53", name: "Chadi Riad", team: "CRY", category: "base-autographs" },
  { number: "BA-54", name: "Eberechi Eze", team: "CRY", category: "base-autographs" },
  { number: "BA-55", name: "Marc Guéhi", team: "CRY", category: "base-autographs" },
  { number: "BA-56", name: "Maxence Lacroix", team: "CRY", category: "base-autographs" },
  { number: "BA-57", name: "Yannick Bolasie", team: "CRY", category: "base-autographs" },
  { number: "BA-58", name: "Iliman Ndiaye", team: "EVE", category: "base-autographs" },
  { number: "BA-59", name: "James Garner", team: "EVE", category: "base-autographs" },
  { number: "BA-60", name: "Jordan Pickford", team: "EVE", category: "base-autographs" },
  { number: "BA-61", name: "Phil Neville", team: "EVE", category: "base-autographs" },
  { number: "BA-62", name: "Yakubu", team: "EVE", category: "base-autographs" },
  { number: "BA-63", name: "Danny Murphy", team: "FUL", category: "base-autographs" },
  { number: "BA-64", name: "Emile Smith Rowe", team: "FUL", category: "base-autographs" },
  { number: "BA-65", name: "Jimmy Bullard", team: "FUL", category: "base-autographs" },
  { number: "BA-66", name: "Josh King", team: "FUL", category: "base-autographs" },
  { number: "BA-67", name: "Louis Saha", team: "FUL", category: "base-autographs" },
  { number: "BA-68", name: "Illan Meslier", team: "LEE", category: "base-autographs" },
  { number: "BA-69", name: "Conor Bradley", team: "LIV", category: "base-autographs" },
  { number: "BA-70", name: "Cody Gakpo", team: "LIV", category: "base-autographs" },
  { number: "BA-71", name: "Diogo Jota", team: "LIV", category: "base-autographs" },
  { number: "BA-72", name: "Emile Heskey", team: "LIV", category: "base-autographs" },
  { number: "BA-73", name: "Harvey Elliott", team: "LIV", category: "base-autographs" },
  { number: "BA-74", name: "John Arne Riise", team: "LIV", category: "base-autographs" },
  { number: "BA-75", name: "Joe Gomez", team: "LIV", category: "base-autographs" },
  { number: "BA-76", name: "Ryan Gravenberch", team: "LIV", category: "base-autographs" },
  { number: "BA-77", name: "Rio Ngumoha", team: "LIV", category: "base-autographs" },
  { number: "BA-78", name: "Virgil van Dijk", team: "LIV", category: "base-autographs" },
  { number: "BA-79", name: "Bernardo Silva", team: "MCI", category: "base-autographs" },
  { number: "BA-80", name: "David Silva", team: "MCI", category: "base-autographs" },
  { number: "BA-81", name: "Emmanuel Adebayor", team: "MCI", category: "base-autographs" },
  { number: "BA-82", name: "Erling Haaland", team: "MCI", category: "base-autographs" },
  { number: "BA-83", name: "Joško Gvardiol", team: "MCI", category: "base-autographs" },
  { number: "BA-84", name: "Joe Hart", team: "MCI", category: "base-autographs" },
  { number: "BA-85", name: "John Stones", team: "MCI", category: "base-autographs" },
  { number: "BA-86", name: "Manuel Akanji", team: "MCI", category: "base-autographs" },
  { number: "BA-87", name: "Mateo Kovačić", team: "MCI", category: "base-autographs" },
  { number: "BA-88", name: "Matheus Nunes", team: "MCI", category: "base-autographs" },
  { number: "BA-89", name: "Micah Richards", team: "MCI", category: "base-autographs" },
  { number: "BA-90", name: "Oscar Bobb", team: "MCI", category: "base-autographs" },
  { number: "BA-91", name: "Phil Foden", team: "MCI", category: "base-autographs" },
  { number: "BA-92", name: "Rúben Dias", team: "MCI", category: "base-autographs" },
  { number: "BA-93", name: "Rico Lewis", team: "MCI", category: "base-autographs" },
  { number: "BA-94", name: "Riyad Mahrez", team: "MCI", category: "base-autographs" },
  { number: "BA-95", name: "Sávio", team: "MCI", category: "base-autographs" },
  { number: "BA-96", name: "Vitor Reis", team: "MCI", category: "base-autographs" },
  { number: "BA-97", name: "André Onana", team: "MUN", category: "base-autographs" },
  { number: "BA-98", name: "Bruno Fernandes", team: "MUN", category: "base-autographs" },
  { number: "BA-99", name: "Diogo Dalot", team: "MUN", category: "base-autographs" },
  { number: "BA-100", name: "Edwin van der Sar", team: "MUN", category: "base-autographs" },
  { number: "BA-101", name: "Gary Neville", team: "MUN", category: "base-autographs" },
  { number: "BA-102", name: "Harry Maguire", team: "MUN", category: "base-autographs" },
  { number: "BA-103", name: "Joshua Zirkzee", team: "MUN", category: "base-autographs" },
  { number: "BA-104", name: "Kobbie Mainoo", team: "MUN", category: "base-autographs" },
  { number: "BA-105", name: "Leny Yoro", team: "MUN", category: "base-autographs" },
  { number: "BA-106", name: "Mason Mount", team: "MUN", category: "base-autographs" },
  { number: "BA-107", name: "Manuel Ugarte", team: "MUN", category: "base-autographs" },
  { number: "BA-108", name: "Nemanja Vidić", team: "MUN", category: "base-autographs" },
  { number: "BA-109", name: "Patrice Evra", team: "MUN", category: "base-autographs" },
  { number: "BA-110", name: "Paul Scholes", team: "MUN", category: "base-autographs" },
  { number: "BA-111", name: "Shea Lacey", team: "MUN", category: "base-autographs" },
  { number: "BA-112", name: "Anthony Gordon", team: "NEW", category: "base-autographs" },
  { number: "BA-113", name: "Bruno Guimarães", team: "NEW", category: "base-autographs" },
  { number: "BA-114", name: "Harvey Barnes", team: "NEW", category: "base-autographs" },
  { number: "BA-115", name: "Lewis Hall", team: "NEW", category: "base-autographs" },
  { number: "BA-116", name: "Lewis Miley", team: "NEW", category: "base-autographs" },
  { number: "BA-117", name: "Nick Pope", team: "NEW", category: "base-autographs" },
  { number: "BA-118", name: "Sven Botman", team: "NEW", category: "base-autographs" },
  { number: "BA-119", name: "Shay Given", team: "NEW", category: "base-autographs" },
  { number: "BA-120", name: "Sandro Tonali", team: "NEW", category: "base-autographs" },
  { number: "BA-121", name: "Tino Livramento", team: "NEW", category: "base-autographs" },
  { number: "BA-122", name: "Anthony Elanga", team: "NFO", category: "base-autographs" },
  { number: "BA-123", name: "Chris Wood", team: "NFO", category: "base-autographs" },
  { number: "BA-124", name: "Matz Sels", team: "NFO", category: "base-autographs" },
  { number: "BA-125", name: "Neco Williams", team: "NFO", category: "base-autographs" },
  { number: "BA-126", name: "Zach Abbott", team: "NFO", category: "base-autographs" },
  { number: "BA-127", name: "Archie Gray", team: "TOT", category: "base-autographs" },
  { number: "BA-128", name: "Cristian Romero", team: "TOT", category: "base-autographs" },
  { number: "BA-129", name: "Dejan Kulusevski", team: "TOT", category: "base-autographs" },
  { number: "BA-130", name: "Dominic Solanke", team: "TOT", category: "base-autographs" },
  { number: "BA-131", name: "Destiny Udogie", team: "TOT", category: "base-autographs" },
  { number: "BA-132", name: "Gareth Bale", team: "TOT", category: "base-autographs" },
  { number: "BA-133", name: "James Maddison", team: "TOT", category: "base-autographs" },
  { number: "BA-134", name: "Lucas Bergvall", team: "TOT", category: "base-autographs" },
  { number: "BA-135", name: "Ledley King", team: "TOT", category: "base-autographs" },
  { number: "BA-136", name: "Mikey Moore", team: "TOT", category: "base-autographs" },
  { number: "BA-137", name: "Son Heung-Min", team: "TOT", category: "base-autographs" },
  { number: "BA-138", name: "Teddy Sheringham", team: "TOT", category: "base-autographs" },
  { number: "BA-139", name: "Will Lankshear", team: "TOT", category: "base-autographs" },
  { number: "BA-140", name: "Yang Min-hyeok", team: "TOT", category: "base-autographs" },
  { number: "BA-141", name: "Aaron Wan-Bissaka", team: "WHU", category: "base-autographs" },
  { number: "BA-142", name: "Bobby Zamora", team: "WHU", category: "base-autographs" },
  { number: "BA-143", name: "Emerson Palmieri", team: "WHU", category: "base-autographs" },
  { number: "BA-144", name: "Jarrod Bowen", team: "WHU", category: "base-autographs" },
  { number: "BA-145", name: "Joe Cole", team: "WHU", category: "base-autographs" },
  { number: "BA-146", name: "Jean-Clair Todibo", team: "WHU", category: "base-autographs" },
  { number: "BA-147", name: "Luis Guilherme", team: "WHU", category: "base-autographs" },
  { number: "BA-148", name: "Lewis Orford", team: "WHU", category: "base-autographs" },
  { number: "BA-149", name: "Mohammed Kudus", team: "WHU", category: "base-autographs" },
  { number: "BA-150", name: "Maximilian Kilman", team: "WHU", category: "base-autographs" },
  { number: "BA-151", name: "Yossi Benayoun", team: "WHU", category: "base-autographs" },
  { number: "BA-152", name: "Jørgen Strand Larsen", team: "WOL", category: "base-autographs" },
  { number: "BA-153", name: "Matheus Cunha", team: "WOL", category: "base-autographs" },
  { number: "BA-154", name: "Tommy Doyle", team: "WOL", category: "base-autographs" },
  { number: "BMA-1", name: "Evanilson", team: "BOU", category: "beast-mode-autographs" },
  { number: "BMA-2", name: "Declan Rice", team: "ARS", category: "beast-mode-autographs" },
  { number: "BMA-3", name: "Georginio Rutter", team: "BHA", category: "beast-mode-autographs" },
  { number: "BMA-4", name: "Hannibal", team: "BUR", category: "beast-mode-autographs" },
  { number: "BMA-5", name: "Enzo Fernández", team: "CHE", category: "beast-mode-autographs" },
  { number: "BMA-6", name: "John Terry", team: "CHE", category: "beast-mode-autographs" },
  { number: "BMA-7", name: "Beto", team: "EVE", category: "beast-mode-autographs" },
  { number: "BMA-8", name: "Daniel James", team: "LEE", category: "beast-mode-autographs" },
  { number: "BMA-9", name: "Virgil van Dijk", team: "LIV", category: "beast-mode-autographs" },
  { number: "BMA-10", name: "Rodri", team: "MCI", category: "beast-mode-autographs" },
  { number: "BMA-11", name: "Alejandro Garnacho", team: "MUN", category: "beast-mode-autographs" },
  { number: "BMA-12", name: "Sandro Tonali", team: "NEW", category: "beast-mode-autographs" },
  { number: "BMA-13", name: "Chris Wood", team: "NFO", category: "beast-mode-autographs" },
  { number: "BMA-14", name: "Dominic Solanke", team: "TOT", category: "beast-mode-autographs" },
  { number: "BMA-15", name: "Ledley King", team: "TOT", category: "beast-mode-autographs" },
  { number: "BMA-16", name: "Emerson Palmieri", team: "WHU", category: "beast-mode-autographs" },
  { number: "CKA-1", name: "Cesc Fàbregas", team: "ARS", category: "chrome-kings-autographs" },
  { number: "CKA-2", name: "Dwight Yorke", team: "AVL", category: "chrome-kings-autographs" },
  { number: "CKA-3", name: "Didier Drogba", team: "CHE", category: "chrome-kings-autographs" },
  { number: "CKA-4", name: "Gianfranco Zola", team: "CHE", category: "chrome-kings-autographs" },
  { number: "CKA-5", name: "Julián Speroni", team: "CRY", category: "chrome-kings-autographs" },
  { number: "CKA-6", name: "Nathaniel Clyne", team: "CRY", category: "chrome-kings-autographs" },
  { number: "CKA-7", name: "Leighton Baines", team: "EVE", category: "chrome-kings-autographs" },
  { number: "CKA-8", name: "Danny Murphy", team: "FUL", category: "chrome-kings-autographs" },
  { number: "CKA-9", name: "Jimmy Floyd Hasselbaink", team: "LEE", category: "chrome-kings-autographs" },
  { number: "CKA-10", name: "Steven Gerrard", team: "LIV", category: "chrome-kings-autographs" },
  { number: "CKA-11", name: "Xabi Alonso", team: "LIV", category: "chrome-kings-autographs" },
  { number: "CKA-12", name: "David Silva", team: "MCI", category: "chrome-kings-autographs" },
  { number: "CKA-13", name: "Sergio Agüero", team: "MCI", category: "chrome-kings-autographs" },
  { number: "CKA-14", name: "Nemanja Vidić", team: "MUN", category: "chrome-kings-autographs" },
  { number: "CKA-15", name: "Wayne Rooney", team: "MUN", category: "chrome-kings-autographs" },
  { number: "CKA-16", name: "Andy Cole", team: "NEW", category: "chrome-kings-autographs" },
  { number: "CKA-17", name: "Roy Keane", team: "NFO", category: "chrome-kings-autographs" },
  { number: "CKA-18", name: "Gareth Bale", team: "TOT", category: "chrome-kings-autographs" },
  { number: "CKA-19", name: "Bobby Zamora", team: "WHU", category: "chrome-kings-autographs" },
  { number: "CKA-20", name: "Paul Ince", team: "WOL", category: "chrome-kings-autographs" },
  { number: "BEA-1", name: "Cole Palmer", team: "CHE", category: "black-edge-autographs" },
  { number: "BEA-2", name: "Eberechi Eze", team: "CRY", category: "black-edge-autographs" },
  { number: "BEA-3", name: "Clint Dempsey", team: "FUL", category: "black-edge-autographs" },
  { number: "BEA-4", name: "Fernando Torres", team: "LIV", category: "black-edge-autographs" },
  { number: "BEA-5", name: "Rio Ngumoha", team: "LIV", category: "black-edge-autographs" },
  { number: "BEA-6", name: "Erling Haaland", team: "MCI", category: "black-edge-autographs" },
  { number: "BEA-7", name: "Alan Shearer", team: "NEW", category: "black-edge-autographs" },
  { number: "BEA-8", name: "Chris Wood", team: "NFO", category: "black-edge-autographs" },
  { number: "BEA-9", name: "Son Heung-Min", team: "TOT", category: "black-edge-autographs" },
  { number: "BEA-10", name: "Matheus Cunha", team: "WOL", category: "black-edge-autographs" },
  { number: "PR-1", name: "Evanilson", team: "BOU", category: "premier-relics" },
  { number: "PR-2", name: "Emiliano Martínez", team: "AVL", category: "premier-relics" },
  { number: "PR-3", name: "Kristoffer Ajer", team: "BRE", category: "premier-relics" },
  { number: "PR-4", name: "Nathan Collins", team: "BRE", category: "premier-relics" },
  { number: "PR-5", name: "Lewis Dunk", team: "BHA", category: "premier-relics" },
  { number: "PR-6", name: "Simon Adingra", team: "BHA", category: "premier-relics" },
  { number: "PR-7", name: "Didier Drogba", team: "CHE", category: "premier-relics" },
  { number: "PR-8", name: "Enzo Fernández", team: "CHE", category: "premier-relics" },
  { number: "PR-9", name: "Harrison Murray-Campbell", team: "CHE", category: "premier-relics" },
  { number: "PR-10", name: "Hernán Crespo", team: "CHE", category: "premier-relics" },
  { number: "PR-11", name: "John Terry", team: "CHE", category: "premier-relics" },
  { number: "PR-12", name: "Levi Colwill", team: "CHE", category: "premier-relics" },
  { number: "PR-13", name: "Malo Gusto", team: "CHE", category: "premier-relics" },
  { number: "PR-14", name: "Nicolas Jackson", team: "CHE", category: "premier-relics" },
  { number: "PR-15", name: "Chris Richards", team: "CRY", category: "premier-relics" },
  { number: "PR-16", name: "Eberechi Eze", team: "CRY", category: "premier-relics" },
  { number: "PR-17", name: "Beto", team: "EVE", category: "premier-relics" },
  { number: "PR-18", name: "Antonee Robinson", team: "FUL", category: "premier-relics" },
  { number: "PR-19", name: "Emile Smith Rowe", team: "FUL", category: "premier-relics" },
  { number: "PR-20", name: "Cody Gakpo", team: "LIV", category: "premier-relics" },
  { number: "PR-21", name: "Conor Bradley", team: "LIV", category: "premier-relics" },
  { number: "PR-22", name: "Darwin Núñez", team: "LIV", category: "premier-relics" },
  { number: "PR-23", name: "Diogo Jota", team: "LIV", category: "premier-relics" },
  { number: "PR-24", name: "Harry Kewell", team: "LIV", category: "premier-relics" },
  { number: "PR-25", name: "Harvey Elliott", team: "LIV", category: "premier-relics" },
  { number: "PR-26", name: "Luis Suárez", team: "LIV", category: "premier-relics" },
  { number: "PR-27", name: "Mohamed Salah", team: "LIV", category: "premier-relics" },
  { number: "PR-28", name: "Virgil van Dijk", team: "LIV", category: "premier-relics" },
  { number: "PR-29", name: "Bernardo Silva", team: "MCI", category: "premier-relics" },
  { number: "PR-30", name: "Ederson", team: "MCI", category: "premier-relics" },
  { number: "PR-31", name: "Erling Haaland", team: "MCI", category: "premier-relics" },
  { number: "PR-32", name: "Jack Grealish", team: "MCI", category: "premier-relics" },
  { number: "PR-33", name: "Jérémy Doku", team: "MCI", category: "premier-relics" },
  { number: "PR-34", name: "John Stones", team: "MCI", category: "premier-relics" },
  { number: "PR-35", name: "Nathan Aké", team: "MCI", category: "premier-relics" },
  { number: "PR-36", name: "Phil Foden", team: "MCI", category: "premier-relics" },
  { number: "PR-37", name: "Rúben Dias", team: "MCI", category: "premier-relics" },
  { number: "PR-38", name: "Sávio", team: "MCI", category: "premier-relics" },
  { number: "PR-39", name: "Alejandro Garnacho", team: "MUN", category: "premier-relics" },
  { number: "PR-40", name: "Diogo Dalot", team: "MUN", category: "premier-relics" },
  { number: "PR-41", name: "Kobbie Mainoo", team: "MUN", category: "premier-relics" },
  { number: "PR-42", name: "Manuel Ugarte", team: "MUN", category: "premier-relics" },
  { number: "PR-43", name: "Paul Ince", team: "MUN", category: "premier-relics" },
  { number: "PR-44", name: "Rasmus Højlund", team: "MUN", category: "premier-relics" },
  { number: "PR-45", name: "Zlatan Ibrahimović", team: "MUN", category: "premier-relics" },
  { number: "PR-46", name: "Alexander Isak", team: "NEW", category: "premier-relics" },
  { number: "PR-47", name: "Lewis Hall", team: "NEW", category: "premier-relics" },
  { number: "PR-48", name: "Lewis Miley", team: "NEW", category: "premier-relics" },
  { number: "PR-49", name: "Tino Livramento", team: "NEW", category: "premier-relics" },
  { number: "PR-50", name: "Cristian Romero", team: "TOT", category: "premier-relics" },
  { number: "PR-51", name: "Mikey Moore", team: "TOT", category: "premier-relics" },
  { number: "PR-52", name: "Son Heung-Min", team: "TOT", category: "premier-relics" },
  { number: "PR-53", name: "Aaron Wan-Bissaka", team: "WHU", category: "premier-relics" },
  { number: "PR-54", name: "Crysencio Summerville", team: "WHU", category: "premier-relics" },
  { number: "PR-55", name: "Emerson Palmieri", team: "WHU", category: "premier-relics" },
  { number: "PR-56", name: "Guido Rodríguez", team: "WHU", category: "premier-relics" },
  { number: "PR-57", name: "Lewis Orford", team: "WHU", category: "premier-relics" },
  { number: "PR-58", name: "Maximilian Kilman", team: "WHU", category: "premier-relics" },
  { number: "PR-59", name: "Niclas Füllkrug", team: "WHU", category: "premier-relics" },
  { number: "PR-60", name: "Matheus Cunha", team: "WOL", category: "premier-relics" },
  { number: "CK 1", name: "Cesc Fàbregas", team: "ARS", category: "chrome-kings" },
  { number: "CK 2", name: "Dwight Yorke", team: "AVL", category: "chrome-kings" },
  { number: "CK 3", name: "Adam Smith", team: "BOU", category: "chrome-kings" },
  { number: "CK 4", name: "Christian Nørgaard", team: "BRE", category: "chrome-kings" },
  { number: "CK 5", name: "Lewis Dunk", team: "BHA", category: "chrome-kings" },
  { number: "CK 6", name: "Gianfranco Zola", team: "CHE", category: "chrome-kings" },
  { number: "CK 7", name: "Didier Drogba", team: "CHE", category: "chrome-kings" },
  { number: "CK 8", name: "Nathaniel Clyne", team: "CRY", category: "chrome-kings" },
  { number: "CK 9", name: "Séamus Coleman", team: "EVE", category: "chrome-kings" },
  { number: "CK 10", name: "Clint Dempsey", team: "FUL", category: "chrome-kings" },
  { number: "CK 11", name: "Xabi Alonso", team: "LIV", category: "chrome-kings" },
  { number: "CK 12", name: "Steven Gerrard", team: "LIV", category: "chrome-kings" },
  { number: "CK 13", name: "David Silva", team: "MCI", category: "chrome-kings" },
  { number: "CK 14", name: "Sergio Agüero", team: "MCI", category: "chrome-kings" },
  { number: "CK 15", name: "Nemanja Vidić", team: "MUN", category: "chrome-kings" },
  { number: "CK 16", name: "Andy Cole", team: "NEW", category: "chrome-kings" },
  { number: "CK 17", name: "Roy Keane", team: "NFO", category: "chrome-kings" },
  { number: "CK 18", name: "Gareth Bale", team: "TOT", category: "chrome-kings" },
  { number: "CK 19", name: "Bobby Zamora", team: "WHU", category: "chrome-kings" },
  { number: "CK 20", name: "Paul Ince", team: "WOL", category: "chrome-kings" },
  { number: "GL 1", name: "Bukayo Saka", team: "ARS", category: "gold-lions" },
  { number: "GL 2", name: "Ollie Watkins", team: "AVL", category: "gold-lions" },
  { number: "GL 3", name: "Evanilson", team: "BOU", category: "gold-lions" },
  { number: "GL 4", name: "Bryan Mbeumo", team: "BRE", category: "gold-lions" },
  { number: "GL 5", name: "Kaoru Mitoma", team: "BHA", category: "gold-lions" },
  { number: "GL 6", name: "Cole Palmer", team: "CHE", category: "gold-lions" },
  { number: "GL 7", name: "Eden Hazard", team: "CHE", category: "gold-lions" },
  { number: "GL 8", name: "Eberechi Eze", team: "CRY", category: "gold-lions" },
  { number: "GL 9", name: "Iliman Ndiaye", team: "EVE", category: "gold-lions" },
  { number: "GL 10", name: "Amad", team: "MUN", category: "gold-lions" },
  { number: "GL 11", name: "Mohamed Salah", team: "LIV", category: "gold-lions" },
  { number: "GL 12", name: "Erling Haaland", team: "MCI", category: "gold-lions" },
  { number: "GL 13", name: "Alejandro Garnacho", team: "MUN", category: "gold-lions" },
  { number: "GL 14", name: "Alexander Isak", team: "NEW", category: "gold-lions" },
  { number: "GL 15", name: "Morgan Gibbs-White", team: "NFO", category: "gold-lions" },
  { number: "GL 16", name: "Son Heung-Min", team: "TOT", category: "gold-lions" },
  { number: "GL 17", name: "Jarrod Bowen", team: "WHU", category: "gold-lions" },
  { number: "GL 18", name: "Matheus Cunha", team: "WOL", category: "gold-lions" },
  { number: "GL 19", name: "Josh Brownhill", team: "BUR", category: "gold-lions" },
  { number: "GL 20", name: "Ao Tanaka", team: "LEE", category: "gold-lions" },
  { number: "LE 1", name: "David Raya", team: "ARS", category: "classic-limited-editions" },
  { number: "LE 2", name: "Youri Tielemans", team: "AVL", category: "classic-limited-editions" },
  { number: "LE 3", name: "Luis Sinisterra", team: "BOU", category: "classic-limited-editions" },
  { number: "LE 4", name: "Fábio Carvalho", team: "BRE", category: "classic-limited-editions" },
  { number: "LE 5", name: "Pervis Estupiñán", team: "BHA", category: "classic-limited-editions" },
  { number: "LE 6", name: "Pedro Neto", team: "CHE", category: "classic-limited-editions" },
  { number: "LE 7", name: "Jean-Philippe Mateta", team: "CRY", category: "classic-limited-editions" },
  { number: "LE 8", name: "James Tarkowski", team: "EVE", category: "classic-limited-editions" },
  { number: "LE 9", name: "Duncan Ferguson", team: "EVE", category: "classic-limited-editions" },
  { number: "LE 10", name: "Paul Scholes", team: "MUN", category: "classic-limited-editions" },
  { number: "LE 11", name: "Alisson Becker", team: "LIV", category: "classic-limited-editions" },
  { number: "LE 12", name: "Bernardo Silva", team: "MCI", category: "classic-limited-editions" },
  { number: "LE 13", name: "Leny Yoro", team: "MUN", category: "classic-limited-editions" },
  { number: "LE 14", name: "Lewis Hall", team: "NEW", category: "classic-limited-editions" },
  { number: "LE 15", name: "Elliot Anderson", team: "NFO", category: "classic-limited-editions" },
  { number: "LE 16", name: "Micky van de Ven", team: "TOT", category: "classic-limited-editions" },
  { number: "LE 17", name: "Aaron Wan-Bissaka", team: "WHU", category: "classic-limited-editions" },
  { number: "LE 18", name: "Rayan Aït-Nouri", team: "WOL", category: "classic-limited-editions" },
  { number: "LE 19", name: "Connor Roberts", team: "BUR", category: "classic-limited-editions" },
  { number: "LE 20", name: "Brenden Aaronson", team: "LEE", category: "classic-limited-editions" },
  { number: "GM 1", name: "Ollie Watkins", team: "AVL", category: "goal-machine" },
  { number: "GM 2", name: "Erling Haaland", team: "MCI", category: "goal-machine" },
  { number: "GM 3", name: "Chris Wood", team: "NFO", category: "goal-machine" },
  { number: "WC 1", name: "Martin Ødegaard", team: "ARS", category: "globaller" },
  { number: "WC 2", name: "Cole Palmer", team: "CHE", category: "globaller" },
  { number: "WC 3", name: "Alexis Mac Allister", team: "LIV", category: "globaller" },
  { number: "BGB 1", name: "Bukayo Saka", team: "ARS", category: "big-game-baller" },
  { number: "BGB 2", name: "Luis Díaz", team: "LIV", category: "big-game-baller" },
  { number: "BGB 3", name: "Bruno Fernandes", team: "MUN", category: "big-game-baller" },
  { number: "HOF 1", name: "Frank Lampard", team: "CHE", category: "hall-of-fame" },
  { number: "HOF 2", name: "Steven Gerrard", team: "LIV", category: "hall-of-fame" },
  { number: "HOF 3", name: "Eric Cantona", team: "MUN", category: "hall-of-fame" },
  { number: "HOF 4", name: "Dennis Bergkamp", team: "ARS", category: "hall-of-fame" },
  { number: "HOF 5", name: "Sergio Agüero", team: "MCI", category: "hall-of-fame" },
  { number: "HOF 6", name: "Rio Ferdinand", team: "MUN", category: "hall-of-fame" },
  { number: "HOF 7", name: "Patrick Vieira", team: "ARS", category: "hall-of-fame" },
  { number: "HOF 8", name: "John Terry", team: "CHE", category: "hall-of-fame" },
  { number: "HOF 9", name: "Roy Keane", team: "MUN", category: "hall-of-fame" },
  { number: "GB 1", name: "Thierry Henry", team: "ARS", category: "golden-boot" },
  { number: "GB 2", name: "Didier Drogba", team: "CHE", category: "golden-boot" },
  { number: "GB 3", name: "Michael Owen", team: "LIV", category: "golden-boot" },
  { number: "GB 4", name: "Mohamed Salah", team: "LIV", category: "golden-boot" },
  { number: "GB 5", name: "Erling Haaland", team: "MCI", category: "golden-boot" },
  { number: "GB 6", name: "Andy Cole", team: "NEW", category: "golden-boot" },
  { number: "GB 7", name: "Alan Shearer", team: "NEW", category: "golden-boot" },
  { number: "FF 1", name: "Jordan Pickford", team: "EVE", category: "festive-freeze" },
  { number: "FF 2", name: "Tariq Lamptey", team: "BHA", category: "festive-freeze" },
  { number: "FF 3", name: "Leighton Baines", team: "EVE", category: "festive-freeze" },
  { number: "FF 4", name: "Virgil van Dijk", team: "LIV", category: "festive-freeze" },
  { number: "FF 5", name: "Maxime Estève", team: "BUR", category: "festive-freeze" },
  { number: "FF 6", name: "Marc Guéhi", team: "CRY", category: "festive-freeze" },
  { number: "FF 7", name: "Bukayo Saka", team: "ARS", category: "festive-freeze" },
  { number: "FF 8", name: "Steven Gerrard", team: "LIV", category: "festive-freeze" },
  { number: "FF 9", name: "Erling Haaland", team: "MCI", category: "festive-freeze" },
  { number: "FF 10", name: "Sergio Agüero", team: "MCI", category: "festive-freeze" },
  { number: "FF 11", name: "Yoane Wissa", team: "BRE", category: "festive-freeze" },
  { number: "FF 12", name: "Tyler Adams", team: "BOU", category: "festive-freeze" },
  { number: "FF 13", name: "Michael Ballack", team: "CHE", category: "festive-freeze" },
  { number: "FF 14", name: "Alexander Isak", team: "NEW", category: "festive-freeze" },
  { number: "FF 15", name: "Nemanja Vidić", team: "MUN", category: "festive-freeze" },
  { number: "FF 16", name: "Amad", team: "MUN", category: "festive-freeze" },
  { number: "FF 17", name: "Yankuba Minteh", team: "BHA", category: "festive-freeze" },
  { number: "FF 18", name: "Emile Heskey", team: "AVL", category: "festive-freeze" },
  { number: "FF 19", name: "Dominic Solanke", team: "TOT", category: "festive-freeze" },
  { number: "FF 20", name: "Jarrod Bowen", team: "WHU", category: "festive-freeze" },
  { number: "FF 21", name: "Anthony Elanga", team: "NFO", category: "festive-freeze" },
  { number: "FF 22", name: "Nélson Semedo", team: "WOL", category: "festive-freeze" },
  { number: "FF 23", name: "Emiliano Martínez", team: "AVL", category: "festive-freeze" },
  { number: "FF 24", name: "Reece James", team: "CHE", category: "festive-freeze" },
  { number: "DRC-1", name: "Julio Soler", team: "BOU", category: "diamond-rookie-cards" },
  { number: "DRC-2", name: "Stefanos Tzimas", team: "BHA", category: "diamond-rookie-cards" },
  { number: "DRC-3", name: "Kendry Páez", team: "CHE", category: "diamond-rookie-cards" },
  { number: "DRC-4", name: "Estêvão", team: "CHE", category: "diamond-rookie-cards" },
  { number: "DRC-5", name: "Romain Esse", team: "CRY", category: "diamond-rookie-cards" },
  { number: "DRC-6", name: "Rio Ngumoha", team: "LIV", category: "diamond-rookie-cards" },
  { number: "DRC-7", name: "Claudio Echeverri", team: "MCI", category: "diamond-rookie-cards" },
  { number: "DRC-8", name: "Reigan Heskey", team: "MCI", category: "diamond-rookie-cards" },
  { number: "DRC-9", name: "Sékou Koné", team: "MUN", category: "diamond-rookie-cards" },
  { number: "DRC-10", name: "Shea Lacey", team: "MUN", category: "diamond-rookie-cards" },
  { number: "PP-1", name: "Declan Rice", team: "ARS", category: "premier-pulls" },
  { number: "PP-2", name: "Jacob Ramsey", team: "AVL", category: "premier-pulls" },
  { number: "PP-3", name: "Justin Kluivert", team: "BOU", category: "premier-pulls" },
  { number: "PP-4", name: "Gustavo Nunes", team: "BRE", category: "premier-pulls" },
  { number: "PP-5", name: "Stefanos Tzimas", team: "BHA", category: "premier-pulls" },
  { number: "PP-6", name: "Estêvão", team: "CHE", category: "premier-pulls" },
  { number: "PP-7", name: "Marc Guéhi", team: "CRY", category: "premier-pulls" },
  { number: "PP-8", name: "Jarrad Branthwaite", team: "EVE", category: "premier-pulls" },
  { number: "PP-9", name: "John Terry", team: "CHE", category: "premier-pulls" },
  { number: "PP-10", name: "Cody Gakpo", team: "LIV", category: "premier-pulls" },
  { number: "PP-11", name: "Abdukodir Khusanov", team: "MCI", category: "premier-pulls" },
  { number: "PP-12", name: "Nico González", team: "MCI", category: "premier-pulls" },
  { number: "PP-13", name: "Kobbie Mainoo", team: "MUN", category: "premier-pulls" },
  { number: "PP-14", name: "Eric Cantona", team: "MUN", category: "premier-pulls" },
  { number: "PP-15", name: "Bruno Guimarães", team: "NEW", category: "premier-pulls" },
  { number: "PP-16", name: "Zach Abbott", team: "NFO", category: "premier-pulls" },
  { number: "PP-17", name: "Lucas Bergvall", team: "TOT", category: "premier-pulls" },
  { number: "PP-18", name: "Gonçalo Guedes", team: "WOL", category: "premier-pulls" },
  { number: "PP-19", name: "James Trafford", team: "BUR", category: "premier-pulls" },
  { number: "PP-20", name: "Joël Piroe", team: "LEE", category: "premier-pulls" },
  { number: "BE-1", name: "Ethan Nwaneri", team: "ARS", category: "black-edge-edition" },
  { number: "BE-2", name: "Kai Havertz", team: "ARS", category: "black-edge-edition" },
  { number: "BE-3", name: "Thierry Henry", team: "ARS", category: "black-edge-edition" },
  { number: "BE-4", name: "Ollie Watkins", team: "AVL", category: "black-edge-edition" },
  { number: "BE-5", name: "Donyell Malen", team: "AVL", category: "black-edge-edition" },
  { number: "BE-6", name: "Dion Dublin", team: "AVL", category: "black-edge-edition" },
  { number: "BE-7", name: "Justin Kluivert", team: "BOU", category: "black-edge-edition" },
  { number: "BE-8", name: "Yoane Wissa", team: "BRE", category: "black-edge-edition" },
  { number: "BE-9", name: "Bryan Mbeumo", team: "BRE", category: "black-edge-edition" },
  { number: "BE-10", name: "Matt O’Riley", team: "BHA", category: "black-edge-edition" },
  { number: "BE-11", name: "Danny Welbeck", team: "BHA", category: "black-edge-edition" },
  { number: "BE-12", name: "Kendry Páez", team: "CHE", category: "black-edge-edition" },
  { number: "BE-13", name: "Cole Palmer", team: "CHE", category: "black-edge-edition" },
  { number: "BE-14", name: "Eden Hazard", team: "CHE", category: "black-edge-edition" },
  { number: "BE-15", name: "Eberechi Eze", team: "CRY", category: "black-edge-edition" },
  { number: "BE-16", name: "Eddie Nketiah", team: "CRY", category: "black-edge-edition" },
  { number: "BE-17", name: "Jordan Pickford", team: "EVE", category: "black-edge-edition" },
  { number: "BE-18", name: "Dwight McNeil", team: "EVE", category: "black-edge-edition" },
  { number: "BE-19", name: "Antonee Robinson", team: "FUL", category: "black-edge-edition" },
  { number: "BE-20", name: "Clint Dempsey", team: "FUL", category: "black-edge-edition" },
  { number: "BE-21", name: "Andreas Pereira", team: "FUL", category: "black-edge-edition" },
  { number: "BE-22", name: "Fernando Torres", team: "LIV", category: "black-edge-edition" },
  { number: "BE-23", name: "Rio Ngumoha", team: "LIV", category: "black-edge-edition" },
  { number: "BE-24", name: "Mohamed Salah", team: "LIV", category: "black-edge-edition" },
  { number: "BE-25", name: "Diogo Jota", team: "LIV", category: "black-edge-edition" },
  { number: "BE-26", name: "Claudio Echeverri", team: "MCI", category: "black-edge-edition" },
  { number: "BE-27", name: "Carlos Tevez", team: "MCI", category: "black-edge-edition" },
  { number: "BE-28", name: "Erling Haaland", team: "MCI", category: "black-edge-edition" },
  { number: "BE-29", name: "Omar Marmoush", team: "MCI", category: "black-edge-edition" },
  { number: "BE-30", name: "Kobbie Mainoo", team: "MUN", category: "black-edge-edition" },
  { number: "BE-31", name: "Alejandro Garnacho", team: "MUN", category: "black-edge-edition" },
  { number: "BE-32", name: "Ruud van Nistelrooy", team: "MUN", category: "black-edge-edition" },
  { number: "BE-33", name: "Bruno Guimarães", team: "NEW", category: "black-edge-edition" },
  { number: "BE-34", name: "Sandro Tonali", team: "NEW", category: "black-edge-edition" },
  { number: "BE-35", name: "Alan Shearer", team: "NEW", category: "black-edge-edition" },
  { number: "BE-36", name: "Morgan Gibbs-White", team: "NFO", category: "black-edge-edition" },
  { number: "BE-37", name: "Chris Wood", team: "NFO", category: "black-edge-edition" },
  { number: "BE-38", name: "Dejan Kulusevski", team: "TOT", category: "black-edge-edition" },
  { number: "BE-39", name: "Son Heung-Min", team: "TOT", category: "black-edge-edition" },
  { number: "BE-40", name: "Dimitar Berbatov", team: "TOT", category: "black-edge-edition" },
  { number: "BE-41", name: "Joe Cole", team: "WHU", category: "black-edge-edition" },
  { number: "BE-42", name: "Luis Guilherme", team: "WHU", category: "black-edge-edition" },
  { number: "BE-43", name: "André", team: "WOL", category: "black-edge-edition" },
  { number: "BE-44", name: "Paul Ince", team: "WOL", category: "black-edge-edition" },
  { number: "BE-45", name: "Matheus Cunha", team: "WOL", category: "black-edge-edition" },
  { number: "BE-46", name: "Josh Brownhill", team: "BUR", category: "black-edge-edition" },
  { number: "BE-47", name: "Marcus Edwards", team: "BUR", category: "black-edge-edition" },
  { number: "BE-48", name: "Wilfried Gnonto", team: "LEE", category: "black-edge-edition" },
  { number: "BE-49", name: "Daniel James", team: "LEE", category: "black-edge-edition" },
  { number: "BE-50", name: "Jimmy Floyd Hasselbaink", team: "LEE", category: "black-edge-edition" },
  { number: "PS-1", name: "Martin Ødegaard", team: "ARS", category: "perfect-storm" },
  { number: "PS-2", name: "Morgan Rogers", team: "AVL", category: "perfect-storm" },
  { number: "PS-3", name: "Tyler Adams", team: "BOU", category: "perfect-storm" },
  { number: "PS-4", name: "Bryan Mbeumo", team: "BRE", category: "perfect-storm" },
  { number: "PS-5", name: "João Pedro", team: "BHA", category: "perfect-storm" },
  { number: "PS-6", name: "Estêvão", team: "CHE", category: "perfect-storm" },
  { number: "PS-7", name: "EberechiEze", team: "CRY", category: "perfect-storm" },
  { number: "PS-8", name: "Dwight McNeil", team: "EVE", category: "perfect-storm" },
  { number: "PS-9", name: "Darwin Núñez", team: "LIV", category: "perfect-storm" },
  { number: "PS-10", name: "Mohamed Salah", team: "LIV", category: "perfect-storm" },
  { number: "PS-11", name: "Luis Suárez", team: "LIV", category: "perfect-storm" },
  { number: "PS-12", name: "Erling Haaland", team: "MCI", category: "perfect-storm" },
  { number: "PS-13", name: "Amad", team: "MUN", category: "perfect-storm" },
  { number: "PS-14", name: "Alexander Isak", team: "NEW", category: "perfect-storm" },
  { number: "PS-15", name: "Anthony Elanga", team: "NFO", category: "perfect-storm" },
  { number: "PS-16", name: "Dominic Solanke", team: "TOT", category: "perfect-storm" },
  { number: "PS-17", name: "Mohammed Kudus", team: "WHU", category: "perfect-storm" },
  { number: "PS-18", name: "João Gomes", team: "WOL", category: "perfect-storm" },
  { number: "PS-19", name: "Luca Koleosho", team: "BUR", category: "perfect-storm" },
  { number: "PS-20", name: "Brenden Aaronson", team: "LEE", category: "perfect-storm" },
  { number: "HV-1", name: "Bukayo Saka", team: "ARS", category: "heat-vision" },
  { number: "HV-2", name: "Donyell Malen", team: "AVL", category: "heat-vision" },
  { number: "HV-3", name: "Antoine Semenyo", team: "BOU", category: "heat-vision" },
  { number: "HV-4", name: "Yoane Wissa", team: "BRE", category: "heat-vision" },
  { number: "HV-5", name: "Kaoru Mitoma", team: "BHA", category: "heat-vision" },
  { number: "HV-6", name: "Cole Palmer", team: "CHE", category: "heat-vision" },
  { number: "HV-7", name: "Romain Esse", team: "CRY", category: "heat-vision" },
  { number: "HV-8", name: "Iliman Ndiaye", team: "EVE", category: "heat-vision" },
  { number: "HV-9", name: "Louis Saha", team: "FUL", category: "heat-vision" },
  { number: "HV-10", name: "Luis Díaz", team: "LIV", category: "heat-vision" },
  { number: "HV-11", name: "Omar Marmoush", team: "MCI", category: "heat-vision" },
  { number: "HV-12", name: "Shea Lacey", team: "MUN", category: "heat-vision" },
  { number: "HV-13", name: "Wayne Rooney", team: "MUN", category: "heat-vision" },
  { number: "HV-14", name: "Anthony Gordon", team: "NEW", category: "heat-vision" },
  { number: "HV-15", name: "Callum Hudson-Odoi", team: "NFO", category: "heat-vision" },
  { number: "HV-16", name: "Brennan Johnson", team: "TOT", category: "heat-vision" },
  { number: "HV-17", name: "Jarrod Bowen", team: "WHU", category: "heat-vision" },
  { number: "HV-18", name: "Matheus Cunha", team: "WOL", category: "heat-vision" },
  { number: "HV-19", name: "Jaidon Anthony", team: "BUR", category: "heat-vision" },
  { number: "HV-20", name: "Ao Tanaka", team: "LEE", category: "heat-vision" },
  { number: "HA-1", name: "Hwang Hee-Chan", team: "WOL", category: "home-advantage" },
  { number: "HA-2", name: "Martin Ødegaard", team: "ARS", category: "home-advantage" },
  { number: "HA-3", name: "Morgan Rogers", team: "AVL", category: "home-advantage" },
  { number: "HA-4", name: "Antoine Semenyo", team: "BOU", category: "home-advantage" },
  { number: "HA-5", name: "Bryan Mbeumo", team: "BRE", category: "home-advantage" },
  { number: "HA-6", name: "João Pedro", team: "BHA", category: "home-advantage" },
  { number: "HA-7", name: "Estêvão", team: "CHE", category: "home-advantage" },
  { number: "HA-8", name: "Didier Drogba", team: "CHE", category: "home-advantage" },
  { number: "HA-9", name: "Eberechi Eze", team: "CRY", category: "home-advantage" },
  { number: "HA-10", name: "Beto", team: "EVE", category: "home-advantage" },
  { number: "HA-11", name: "Steven Gerrard", team: "LIV", category: "home-advantage" },
  { number: "HA-12", name: "Rio Ngumoha", team: "LIV", category: "home-advantage" },
  { number: "HA-13", name: "Yaya Touré", team: "MCI", category: "home-advantage" },
  { number: "HA-14", name: "Erling Haaland", team: "MCI", category: "home-advantage" },
  { number: "HA-15", name: "Bruno Fernandes", team: "MUN", category: "home-advantage" },
  { number: "HA-16", name: "Zlatan Ibrahimović", team: "MUN", category: "home-advantage" },
  { number: "HA-17", name: "Anthony Gordon", team: "NEW", category: "home-advantage" },
  { number: "HA-18", name: "Morgan Gibbs-White", team: "NFO", category: "home-advantage" },
  { number: "HA-19", name: "Son Heung-Min", team: "TOT", category: "home-advantage" },
  { number: "HA-20", name: "Gareth Bale", team: "TOT", category: "home-advantage" },
  { number: "HA-21", name: "Jarrod Bowen", team: "WHU", category: "home-advantage" },
];
